name: behavioral-cloning-env
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - pyqt=4.11.4
    - pip:
        - moviepy
        - opencv-python
        - requests
        - tensorflow-gpu==1.3.0
        - keras==2.2.4
